### PR TITLE
Improve debugging capability and fix steps per angle

### PR DESCRIPTION
**Pull request by sheerun**
This PR does two things:

1. Add additional button in debug mode that switches between implementation of this repository and implementation of JSTS (as implemented in https://github.com/Turfjs/turf/pull/1425)
2. Based on initial feedback of above I've multiplied steps for point by 4 and steps for line by 2 which seems to match JSTS behavior

There are more differences which I'll look into, but I think these two are ready to merge

### CODE REVIEW

**Comment by sheerun** [comment]
I've just pushed extra commit that formats everything with prettier (good formatted code is better to debug)

**Comment by sheerun** [comment]
I've pushed another fix for off-by-one error for rounding linestrings

**Comment by sheerun** [comment]
btw. I've noticed JSTS creates features of lesser radius than turf but if this is a bug on turf side it is also present on utils like `circle` because they seem to have the same radius as this util

**Comment by sheerun** [comment]
Oh I get it now. JSTS doesn't use exact number of points for each angle but reduces it depending on angle. Point gets 4x points because it's "360 degrees angle", end of lines get 2x because they are "180 angle", and for example 20 degree turn gets less points than 80 degree turn. I've updated code so it reflects this.

I think I'm pretty happy with result. Here's before: https://v.usetapes.com/W9ddgLyCsG

And here's after this PR: https://v.usetapes.com/QJcsPeYvh0

**Comment by rowanwins** [comment]
Hi @sheerun 

I've incorporated a fair few of these changes into the [latest deployed docs](https://rowanwins.github.io/geojson-buffer/debug/index.html) (although not all)

Because of the changes I made to the webpack setup it was simpler just to pull them across manually.

I haven't done the vertice counts or marking the vertices in red.

Cheers

**Pull request closed without merging**
